Document: python-nmap
Title: Debian python-nmap Manual
Author: <insert document author here>
Abstract: This manual describes what python-nmap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-nmap/python-nmap.sgml.gz

Format: postscript
Files: /usr/share/doc/python-nmap/python-nmap.ps.gz

Format: text
Files: /usr/share/doc/python-nmap/python-nmap.text.gz

Format: HTML
Index: /usr/share/doc/python-nmap/html/index.html
Files: /usr/share/doc/python-nmap/html/*.html
